# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on:
  pull_request:
    branches:
      - '1.18'
  push:
    branches:
      - '1.18'

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          17    # Minimum supported by Minecraft
        ]
        # and run on both Linux and Windows
        os: [ ubuntu-20.04, windows-latest ]
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[CI-SKIP]')"
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
