name: Qodana
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 1.17
  push:
    branches:
      - 1.17

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Add JDK Settings'
        run: |
          mkdir ./.idea
          cat << EOF > ./.idea/misc.xml
          <?xml version="1.0" encoding="UTF-8"?>
          <project version="4">
          <component name="ExternalStorageConfigurationManager" enabled="true" />
          <component name="FrameworkDetectionExcludesConfiguration">
            <file type="web" url="file://$PROJECT_DIR$" />
          </component>
          <component name="ProjectRootManager" version="2" languageLevel="JDK_17" default="true" project-jdk-name="openjdk-17" project-jdk-type="JavaSDK" />
          </project>
          EOF
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v4.2.3
        with:
          linter: jetbrains/qodana-jvm  # pick the needed linter – https://www.jetbrains.com/help/qodana/docker-images.html
#      - uses: github/codeql-action/upload-sarif@v1
#        with:
#          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
